# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 607bcaaad64fcc08aa1ff19863c6c1930e69a7975f1cf08ca6f532cb12f88856a28258f152037cfb6fc8a039105e5bd6bfff1431fdbec5d6603778a7dec9bbe7

test:
  secret_key_base: 63c32868bd2d5dabffa7ee70bef3f46de13cb04c6f45145ef75fba47c4a54c9578c174429a468a0af6e9a1c724ae5a82cdba1c8a6621f5422d16619f4a31a160

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
